# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.
"""

import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import urllib.request

def imshow(img):
    fig,ax=plt.subplots(1,1,figsize=(8,8))
    ax.imshow(img)

path_img='https://d.newsweek.com/en/full/1809693/cat-dog.jpg?w=1600&h=1600&q=88&f=117239ddc10e0929372035ef0b425e2e'

req=urllib.request.urlopen(path_img)
arr=np.asarray(bytearray(req.read()),dtype=np.uint8)
img =cv2.imdecode(arr,-1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
img=cv2.resize(img,(224,224))

imshow(img)

model = tf.keras.applications.vgg16.VGG16(weights="imagenet", include_top = True)

model.summary()

img_tensor=np.array([img])

img_tensor.shape

np.argmax(model.predict(img_tensor))

# !pip install tf_explain

from tf_explain.core.grad_cam import GradCAM

data=([img],None)

predict_class_index=281#np.argmax(model.predict(img_tensor))

explainer = GradCAM()

heatMap=explainer.explain(data, model,class_index=predict_class_index,layer_name="block5_conv3")

imshow(heatMap)

